server:
  port: 8080

spring:
    
  application:
    name: kakaopay
  datasource:
    platform: mysql
    url: jdbc:mysql://mariadb:3306/work?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: qrwe1423  
    
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: kr.pe.homework.persistence.dao